FROM nvidia/cuda:12.2.0-devel-ubuntu20.04
COPY . /libvgpu
WORKDIR /libvgpu
RUN apt-get -y update; apt-get -y install wget
RUN wget https://cmake.org/files/v3.19/cmake-3.19.8-Linux-x86_64.tar.gz
RUN tar -xf cmake-3.19.8-Linux-x86_64.tar.gz
RUN cp /libvgpu/cmake-3.19.8-Linux-x86_64/bin/cmake /libvgpu/cmake-3.19.8-Linux-x86_64/bin/cmake3
ENV PATH="/libvgpu/cmake-3.19.8-Linux-x86_64/bin:${PATH}"
RUN rm -r ./build
RUN apt-get -y install openssl libssl-dev
RUN bash ./build.sh